home/views.py
import datetime
from flask import Blueprint, render_template, session
from ..extentions import db
from ..products.models import Product, ProductCategory


main = Blueprint('main', __name__, url_prefix='/')


@main.route('/', methods=['GET', 'POST', 'PUT'])
@main.route('/<id>', methods=['GET', 'POST', 'PUT'])
def home(id=None):
    data = {
        'ad_products':  Product.query.all()[::4],
        'products': Product.query.all() if not id \
            else db.session.query(Product).filter(
                Product.product_category.any(ProductCategory.id.in_([id]))),
        'time': datetime.datetime.now(),
        'categories': ProductCategory.query.all(),
    }
    # if request.method == 'POST':
        # search = request.form['search']
        # data['products'] = Product.query.filter(Product.name.contains(search)).all()
    return render_template('home/home.html', **data)

templates/inclusion/flask_messages.html
{% with messages = get_flashed_messages() %}
{% if messages %}
    {% for message in messages %}
        <h5 style="border: 1px solid rgb(137, 137, 221); color: rgb(137, 137, 221); border-radius: 15px; padding: 10px; margin-bottom: -40px;">{{ message }}</h5>
    {% endfor %}
{% endif %}
{% endwith %}

templates/inclusion/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn" style="background-color: rgb(135, 192, 227);">
    <div class="pb-4 pt-4">
        <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank"><i class="fab fa-linkedin mr-3 fab-big"></i></a>
        <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank"><i class="fab fa-github mr-3 fab-big"></i></a>
        <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank"><i class="fab fa-google mr-3 fab-big"></i></a>
        <a href="https://www.facebook.com/mdbootstrap" target="_blank"><i class="fab fa-facebook-f mr-3 fab-big"></i></a>
        <a href="https://twitter.com/MDBootstrap" target="_blank"><i class="fab fa-twitter mr-3 fab-big"></i></a>
    </div>
    <div class="footer-copyright py-3">
        © 2022 Copyrighting Templates via: 
        <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>

</footer>

templates/inclusion/navbar.html
<style>
    .default-user-img:hover {
        opacity: 0.5;
    }
    .active-user {
        padding: 2px;
        border: 2px solid rgba(41, 152, 190, 0.49);
    }
    .inactive-user {
        padding: 2px;
        border: 2px solid rgba(53, 54, 53, 0.272);
    }

    .header-icons:hover {
        opacity: 0.6;
    }
</style>

<nav class="navbar fixed-top navbar-expand-md navbar-light white scrolling-navbar">
    <div class="container">

        <!-- Brand -->
        <a class="navbar-brand waves-effect" href="{{url_for('main.home')}}">
            <strong class="blue-text">FMP</strong>
        </a>

        <!-- Collapse -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Left -->
            <ul class="navbar-nav mr-auto">
                <!-- EMPTY -->
            </ul>

            <!-- Right -->
            <ul class="navbar-nav nav-flex-icons">
                {% if current_user.is_authenticated %}
                    <div class="dropdown">
                        <li class="nav-item">
                            <a href="{{url_for('auth.profile')}}" class="nav-link rounded waves-effect mr-2">{{current_user}}</a>
                        </li>
                        <div class="dropdown-content" style="font-size: 14px;  width: fit-content">
                            {% if current_user.role %}
                                <li class="nav-item">
                                    <a href="{{url_for('create_product')}}" class="nav-link waves-effect mr-2">Create Product</a>
                                </li>
                                <li class="nav-item">
                                    <a href="{{url_for('checkout.marketing_tools')}}" class="nav-link waves-effect mr-2">Marketing Tools</a>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a href="#" class="nav-link waves-effect mr-2">Cart</a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link waves-effect mr-2">Saved</a>
                                </li>
                            {% endif %}
                            <li class="nav-item">
                                <a href="{{url_for('auth.profile')}}" class="nav-link waves-effect mr-2">Settings</a>
                            </li>
                            <li class="nav-item">
                                <a href="{{url_for('auth.logout')}}" class="nav-link waves-effect mr-2">Log Out</a>
                            </li>
                        </div>
                    </div>
                    {% if current_user.status == 'Default' %}
                        <li class="nav-item">
                            <a href="{{url_for('auth.profile')}}">
                                <img src="{{url_for('static', filename=current_user.img)}}"
                                alt="" class="logo active-user">
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{url_for('auth.login_default')}}">
                                <img src="{{url_for('static', filename=session['default_user_img'])}}"
                                alt="" class="logo default-user-img inactive-user">
                            </a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a href="{{url_for('auth.profile')}}">
                                <img src="{{url_for('static', filename=current_user.img)}}"
                                alt="" class="logo">
                            </a>
                        </li>
                    {% endif %}
                    {% if current_user.role %}
                        <li class="nav-item">
                            <a class="nav-link waves-effect" href="{{url_for('create_product')}}">
                                <img src="{{url_for('static', filename='img/app/cart-plus-solid.svg')}}"
                                    alt="" width="19" class="header-icons">
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link waves-effect" href="{{url_for('checkout.marketing_tools')}}">
                                <img src="{{url_for('static', filename='img/app/chart-bar-regular.svg')}}"
                                    alt="" width="19" class="header-icons">
                            </a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link waves-effect" href="{{url_for('card')}}">
                                <i class="fas fa-shopping-cart"></i>
                                {% if current_user.card_id %}
                                    <span
                                        id="cart_badge" class="badge badge-pill danger-color"
                                        style="display: inline-block; padding: 4px; margin: 0 0 10px -7px;"
                                    ></span>
                                {% endif %}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link waves-effect" href="{{url_for('card')}}">
                                <img src="{{url_for('static', filename='img/app/bookmark-regular.svg')}}"
                                    alt="" width="13" style="margin-top: -5px" class="header-icons">
                                {% if current_user.card_id %}
                                    <span
                                        id="cart_badge" class="badge badge-pill danger-color"
                                        style="display: inline-block; padding: 4px; margin: 0 0 10px -7px;"
                                    ></span>
                                {% endif %}
                            </a>
                        </li>
                    {% endif %}
                <div class="dropdown">
                    <li class="nav-item">
                        <a
                            href="#" class="nav-link rounded waves-effect mr-2"
                            style="color: rgb(43, 172, 220); font-size: smaller; margin: 3px 0 0 5px; font-weight: 400;"
                        >USD</a>
                    </li>
                    <div class="dropdown-currency">
                        {% set currencies = ['USD', 'EUR', 'UAH', 'RUB', 'CNY', 'GBP'] %}
                        {% for currency in currencies %}
                                <li class="nav-item">
                                    <a onClick="changeCurrency('{{currency}}')" class="mr-2 waves-effect li-currency">{{currency}}</a>
                                </li>
                        {% endfor %}
                    </div>
                </div>
                {%else%}
                    <li class="nav-item">
                        <a href="{{url_for('auth.register', user='customer')}}" class="nav-link border border-light rounded waves-effect mr-2">Sing Up</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{url_for('auth.login')}}" class="nav-link border border-dark btn-dark rounded waves-effect"><span style="color: #fff">Sing In</span></a>
                    </li>
                {%endif%}
            </ul>

        </div>

    </div>
</nav>

templates/inclusion/pagination.html
<nav class="d-flex justify-content-center wow fadeIn">
    <ul class="pagination pg-blue">
        <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>

        <li class="page-item active">
            <a class="page-link" href="#">1
                <span class="sr-only">(current)</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="#">2</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="#">3</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="#">4</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="#">5</a>
        </li>

        <li class="page-item">
            <a class="page-link" href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
    </ul>
</nav>