checkout/views.py
from locale import currency
import sys
import uuid
import datetime
from xmlrpc.client import boolean
from ..checkout.models import Coupon, Currency, Promotion, DiscountType, CouponType
from ..products.models import Product
from ..extentions import db
from flask.json import jsonify
from flask_login import login_required
from flask import Blueprint, request, render_template, redirect, session, url_for, flash
from flask_login import current_user, login_required
from ..checkout.forms import PromotionForm


checkout = Blueprint('checkout', __name__, url_prefix='/checkout')
promotion = Blueprint('promotion', __name__, url_prefix='/promotion')


@login_required
@checkout.route('/marketing_tools', methods=['GET'])
def marketing_tools():
    data = dict()
    if current_user.promotion:
        data = {
            'promotions': current_user.promotion
        }

    return render_template('promotion/marketing_tools.html', **data)


@checkout.route('/create_promotion', methods=['GET', 'POST'])
def create_promotion():

    form = PromotionForm()
    form.products.data = [str(product.id) for product in Product.query.filter_by(owner=current_user.email)]
    today = datetime.datetime.now()
    data = {
        'form': form,
        'today': today
    }

    if request.method == 'POST':
        try:
            promotion = Promotion(
                title=request.form.get('title'),
                description=request.form.get('description'),
                discount_type=DiscountType[request.form.get('discount_type')],
                discount_value=int(request.form.get('discount_value')),
                coupon_type=CouponType[request.form.get('coupon_type')],
                currency_id=int(request.form.get('currency')),
                start_day=datetime.datetime.strptime(
                     request.form['start_day'][:-6],
                     '%Y-%m-%d'
                     ) if request.form.get('start_day') else None,
                end_day=datetime.datetime.strptime(
                     request.form['end_day'][:-6],
                     '%Y-%m-%d'
                     ) if request.form.get('end_day') else None,
                instant_discount=True if request.form.get('instant_discount') else False,
                active=True if request.form.get('active') else None
            )

            promotion.products.extend([Product.query.get(int(product)) for product in request.form.getlist('products')])

            promotion.save()

            coupons = request.form.get('coupons')
            if coupons:
                for coupon in coupons.splitlines():
                    coupon = Coupon(
                        code=coupon,
                        promotion_id=promotion.id
                    )
                    promotion.coupon.extend([coupon])

                    db.session.add(promotion)
                    db.session.add(coupon)
            else:

                coupon = Coupon(
                    code=str(uuid.uuid4())[:18].replace('-', ''),
                    promotion=promotion
                )
                promotion.coupon.extend([coupon])

                db.session.add(coupon)
                db.session.add(promotion)

            try:
                current_user.promotion.extend([promotion])
                db.session.add(current_user)
                db.session.commit()
                flash('Promotion added')
                return redirect(url_for('checkout.marketing_tools'))
            except Exception as _ex:
                flash(_ex)

        except Exception as _ex:
            flash(_ex)

    else:
        flash('Something went wrong')
    return render_template('promotion/create_promotion.html', **data)


@checkout.route('/generate_coupon', methods=['PUT'])
def generate_coupon():
    if request.method == 'PUT':
        quantity = request.form.get('quantity')
        coupons = list()
        for i in range(int(quantity)):
            coupons.append(str(uuid.uuid4())[:18].replace('-', ''))

        return jsonify(list_of_data=coupons)


@promotion.route('/find_coupon', methods=['PUT'])
def find_coupon():
    if request.method == 'PUT':
        code = request.form.get('code')
        data = dict()
        try:
            coupon = Coupon.query.filter_by(code=code, active=True)[0]
        except:
            coupon = None
        code = coupon.code if coupon else None
        if code:
            data = {
                'promotion': code,
                'title': coupon.promotion.title,
                'value': coupon.promotion.discount_value,
                'type': coupon.promotion.discount_type.name
            }
        return  jsonify(**data)


@promotion.route('/apply_promotion', methods=['POST'])
def apply_promotion():
    if request.method == 'POST':
        coupon = Coupon.query.filter_by(code=request.form.get('code'))[0]
        coupon.active = False
        current_user.coupons.extend([coupon])
        current_user.active_discount = True
        db.session.add(coupon)
        db.session.add(current_user)
        db.session.commit()
        return ('', 204)

templates/promotion/create_promotion.html
{% extends 'base.html' %}

{%block title%}Marketing tools{%endblock%}

{%block extrastyle%}
<style>
  input[type="datetime-local" i] {
    border: 1px solid rgb(186, 185, 185);
    border-radius: 5px;
    padding: 10px;
    color: grey;
    align-items: center;
    display: -webkit-inline-flex;
    padding-inline-start: 1px;
    cursor: default;
    overflow: hidden;
    padding: 0px;
}

</style>
{%endblock%}

{% block script%}
<script src="{{url_for('static', filename='js/promotion.js')}}"></script>
{%endblock%}

{%block content%}
<main class="mt-5 pt-4">
    <div class="container wow fadeIn">
      <h2 class="my-5 h2 text-center">Create Promotion</h2>

      <div class="row">

        <div class="col-8 mx-auto">
          <div class="card">
            <form class="card-body" novalidate action="" method="POST">
                {{csrf_token}}

                <div class="md-form input-group pl-0 mb-5">
                    {{ form.title.label}}
                    {{ form.title(class_="form-control py-2")}}
                </div>
                {% for error in form.title.errors %}
                    <div class="alert" role="alert">
                        {{ error }}
                    </div>
                {% endfor%}

                <div class="md-form input-group pl-0 mb-5">
                    {{ form.description.label}}
                    {{ form.description(class_="form-control py-2")}}
                </div>
                {% for error in form.description.errors %}
                    <div class="alert" role="alert">
                        {{ error }}
                    </div>
                {% endfor%}

                <div class="row">
                    <div class="col-lg-4 col-md-12 mb-4">

                        <div class="md-form input-group pl-0 mb-5">
                            {{ form.discount_value.label}}
                            {{ form.discount_value(class_="form-control py-2")}}
                        </div>
                        {% for error in form.discount_value.errors %}
                            <div class="alert" role="alert">
                                {{ error }}
                            </div>
                        {% endfor%}
                    </div>  

                    <div class="col-lg-2 col-md-6 mb-4">
                      <div class="form-group">
                      {{ form.currency.label(class_="text-muted")}}
                      {{ form.currency(class_="form-control")}}
                      </div>
                      {% for error in form.currency.errors %}
                          <div class="alert" role="alert">
                              {{ error }}
                          </div>
                      {% endfor%}
                    </div>
                    
                    <div class="col-lg-6 col-md-6 mb-4">
                        <div class="form-group">
                            {{ form.discount_type.label(class_="text-muted")}}
                            {{ form.discount_type(class_="form-control")}}
                        </div>
                        {% for error in form.discount_type.errors %}
                            <div class="alert" role="alert">
                                {{ error }}
                            </div>
                        {% endfor%}

                    </div>
                    
                </div>  

                <div class="row">
                    <div class="col-lg-6 col-md-6 mb-4">
                        <div class="form-group">
                            {{ form.coupon_type.label(class_="text-muted")}}
                            {{ form.coupon_type(class_="form-control")}}
                        </div>
                    {% for error in form.coupon_type.errors %}
                        <div class="alert" role="alert">
                            {{ error }}
                        </div>
                    {% endfor%}
                    </div>

                    <div class="col-lg-5 col-md-6 mb-4" id="m_quantity" style="display: none;">
                        <div class="form-group">
                          <label for="quantity" class="text-muted">Quantity</label>
                          <input type="number" id="coupon_quantity" name="quantity" placeholder="" class="form-control" min="0">
                        </div>
                    </div>

                    <div class="col-lg-1 col-md-6 mb-4 mt-4" id="m_button" style="display: none;">
                      <a onclick="generateCoupons()" class="text-muted" style="font-size: large;"><i id="g_button" class="fa fa-check"></i></a>
                    </div>

                </div>
                <div class="form-group mb-5" id="m_coupon" style="display: none;">
                  <textarea id="m_coupons"  name="coupons" id="" cols="30" rows="10" class="form-control"></textarea>
                </div>

                
              <div class="form-group" style="max-width: 330px;">
                  {{ form.products.label(class_="text-muted")}}
                  {{ form.products(class_="form-control")}}
              </div>
              {% for error in form.products.errors %}
                  <div class="alert" role="alert">
                      {{ error }}
                  </div>
              {% endfor%}

              <div class="row" style="margin-top: 40px;">

                <div class="col-lg-6 col-md-6 mb-4">
                  <div class="form-group datetime">
                    <label for="start_day" class="text-muted"> Start at</label>
                    <div>
                      <input type="datetime-local" id="start_day"
                    name="start_day"">
                    </div>
                  </div>
                </div>
                
                  <div class="col-lg-6 col-md-6 mb-4">
                    <div class="form-group">
                      <label for="end_day" class="text-muted">End at</label>
                      <div>
                        <input type="datetime-local" id="end_day"
                      name="end_day">
                      </div>
                    </div>
                  </div>

              </div>

              <div class="md-form input-group pl-0 mb-4" id="instant">
                {{ form.instant_discount.label}}
                {{ form.instant_discount(class_="form-control py-2 mt-4", value='True')}}
              </div>
              {% for error in form.instant_discount.errors %}
                  <div class="alert" role="alert">
                      {{ error }}
                  </div>
              {% endfor%}

            <div class="md-form input-group pl-0 mb-5">
              {{ form.active.label}}
              {{ form.active(class_="form-control py-2 mt-4", value='True')}}
            </div>
            {% for error in form.description.errors %}
                <div class="alert" role="alert">
                    {{ error }}
                </div>
            {% endfor%}

              {% with messages = get_flashed_messages() %}
              {% if messages %}
                  {% for message in messages %}
                  <def class="alert" role="alert" style="margin-top: 20px; color: red;">
                      * {{ message }}
                  </def>
                    {% endfor %}
                {% endif %}
              {% endwith %}
              
              <hr class="mb-4">
              <div class="row">
                <div class="col-sm-12">
                  <button class="btn btn-info" type="submit">Submit</button>
                  <a class="btn btn-light" href="{{url_for('create_product')}}">Back</a>
                </div>
              </div>

            </form>
          </div>
        </div>

        </div>
      </div>
    </div>
  </main>
  {%endblock%}

templates/promotion/marketing_tools.html
{% extends 'base.html' %}

{%block title%}Marketing tools{%endblock%}

{%block content%}

{% if current_user.promotion %}
<main class="mt-5 pt-4">
    <div class="container wow fadeIn">
      <h2 class="my-5 h2 text-center">Your promotions</h2>

      <div class="row">
        {% for promotion in promotions %}

        <div class="col-lg-6">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-8">
                            <h5 class="card-title">{{promotion.title}}</h5>
                        </div>
                        <div class="col-sm-4 mx-0 my-2">
                        <h6 class="card-subtitle mb-2 text-muted">
                    {%if promotion.discount_type.name == 'fixed'%} 
                    <span style="font-size: small;">{{promotion.currency}}</span> 
                    {%endif%}
                    {{promotion.discount_value}}
                    {%if promotion.discount_type.name == 'persent'%}%{%endif%}</h6>
                        </div>
                    </div>
                
                {% if promotion.description %}
                <p class="card-text" style="max-width: 200px;">{{promotion.description}}</p>
                {% endif %}
                
                <div class="row">
                    <div class="col-sm-8">
                        <p style="font-size: small;">{%if promotion.coupon_type == 'single'%} Single {% else %} Multiple {%endif%}type</p>
                    </div>
                    <div class="col-sm-4 mx-0">
                        <span style="font-size: small;"><a href="http://">SHOW</a></span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-8">
                        <p style="font-size: small;">Available for {{promotion.count_products()}} products</p>
                    </div>
                    <div class="col-sm-4 mx-0">
                        <span style="font-size: small;"><a href="http://">SHOW</a></span>
                    </div>
                </div>
                {% if promotion.start_day%}
                    <p>{{promotion.start_day}}</p>
                {%endif%}
                {% if promotion.end_day%}
                    <p>{{promotion.end_day}}</p>
                {%endif%}
                <p><a href="">{%if promotion.active%}Activate{%else%}Deactivate{%endif%}</a></p>
                </div>
            </div>
        </div>
      </div>
      
      {% endfor %}
    </div>    
</main>
{% else %}
    <div class="center-block">
        <p style="text-align: center;"><i class="fa fa-code" style="font-size: 840%; margin: 8% 0 7% 0; color: rgb(191, 188, 188); text-shadow: 2px 3px rgb(167, 166, 166); "></i></p>
        <h2 style="color: rgb(191, 188, 188); text-align: center; margin-bottom: 3%;">You have no promotion</h2>
        <p style="text-align: center;"><a href="{{url_for('checkout.create_promotion')}}" class="nav-link border border-light rounded waves-effect mr-2">Add promotion</a></p>
        
    </div>
{% endif %}
{%endblock%}